mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xzj.mysql.mapper
  configuration:
    og-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#123
#logging:
#  file:
#    name: logs/mylog.log
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{50}:%line %msg%n'
#    file: '%d{yyyy-MM-dd HH:mm} -- [%thread] %-5level %logger{50} %msg%n'
## 指定控制台输出的日志格式，如：
## %d{yyyy-MM-dd HH:mm:ss} -- [%thread] %-5level %logger{50} %msg%n
## 1、%d 表示日期时间，
## 2、%thread 表示线程名，
## 3、%‐5level 级别从左显示5个字符宽度
## 4、%logger{50} 表示logger名字最长50个字符，否则按照句点分割。
## 5、%msg 日志消息，
## 6、%n 换行符
## 7、%line 显示日志输出位置的行号，方便寻找位置